### ISSUE TITLE
Cursor gets stuck hidden

### ISSUE THREAD

**Issue by xcloudx01** [setsumi/MousePuff#3]
I'm on Win11, and sometimes when using the program, the mouse cursor will get hidden and it doesn't return. The mouse still functions but is completely invisible until the "Exit" button is clicked on the program's GUI or I log out of Windows. Keeping the mouse still and then moving it again does not trigger the mouse to become visible.
I'd love to see this issue fixed as I like the software otherwise. The bug is very random when it will trigger. I'm using between 1 and 3s hide delay. The hiding is set to "Global" and no program-specific rules have been made.

**Comment by setsumi** [comment]
I think I had a similar issue on Windows 10 but it was so rare, like once per month or so, I couldn't pinpoint it to reproduce. If the issue occurs, I'd like to know if disabling bold "Enabled" option in the GUI, re-enabling it again and moving the mouse will fix the issue or not.

**Comment by xcloudx01** [comment]
Sweet, thanks for the lead on tracking this down. I'll keep you updated on if toggling that fixes it 😊. It's been happening fairly frequently for me so it shouldn't be too long to find out.

**Comment by xcloudx01** [comment]
I've been able to reproduce it. I think it seems to be a bug with the Window's display drivers interfering with MousePuff. Tldr the try toggling Enabled as you suggested did indeed fix it and it restored the cursor :D.

It occurred when I changed the image scaling option in GeForce Experience which made my display refresh and then the mouse cursor was gone. It happened again when I was messing around with resolutions while playing TF2. Both times though I could get the cursor back by activating the MousePuff window either by Alt+Tabbing into it or by clicking the window, and then pressing Ctrl+E. Pressing Ctrl+E without first activating the MousePuff window didn't restore the cursor though.

Hope this helps :3. Upon retrospect I do mess around with settings all the time so maybe that's why it kept happening haha

**Comment by setsumi** [comment]
Oh, this is unexpected scenario but sort of reasonable. Thank you.
Okay I'll try to detect this happenings and restore functionality.

**Comment by setsumi** [comment]
Test version.
https://github.com/setsumi/MousePuff/releases/tag/v1.6.5test1

**Comment by xcloudx01** [comment]
Awesome, thank you for the rapid changes. I'll let you know after using it for a while to confirm if it has worked

**Comment by xcloudx01** [comment]
I believe the issue has been fixed. It hasn't occurred again during the week I've been using the test version. I've even tried to purposefully break it again without success too.

Awesome work, thank you! 😁
