### ISSUE TITLE
Hiding Forever

### ISSUE THREAD

**Issue by hrachkovinovoto** [setsumi/MousePuff#4]
I was wondering if we could hide the cursor indefinitely (even during mouse movement) while an active window is being used and have it revert back to normal as soon as focus to target is lost. I've stumbled upon an old AHK script that does exactly this as long as we specify the window where we wish for the cursor to disappear. Here's to hoping that the same feature can eventually be implemented into MousePuff as well:  

<details><summary>Here is the script</summary>
; Minor edits by Nirklars - https://nirklars.wordpress.com/tag/focus/

SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

SystemCursor("Init")

SetTimer, CheckIdle, 250
return

CheckIdle:
if WinActive("ahk_class XeniaWindowClass") 
{
    SystemCursor("Off")
}
else
{
    SystemCursor("On")
}
return

#Persistent
OnExit, ShowCursor  ; Ensure the cursor is made visible when the script exits.
return

ShowCursor:
SystemCursor("On")
ExitApp

SystemCursor(OnOff=1)   ; INIT = "I","Init"; OFF = 0,"Off"; TOGGLE = -1,"T","Toggle"; ON = others
{
    static AndMask, XorMask, $, h_cursor
        ,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13 ; system cursors
        , b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,b11,b12,b13   ; blank cursors
        , h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11,h12,h13   ; handles of default cursors
    if (OnOff = "Init" or OnOff = "I" or $ = "")       ; init when requested or at first call
    {
        $ = h                                          ; active default cursors
        VarSetCapacity( h_cursor,4444, 1 )
        VarSetCapacity( AndMask, 32*4, 0xFF )
        VarSetCapacity( XorMask, 32*4, 0 )
        system_cursors = 32512,32513,32514,32515,32516,32642,32643,32644,32645,32646,32648,32649,32650
        StringSplit c, system_cursors, `,
        Loop %c0%
        {
            h_cursor   := DllCall( "LoadCursor", "uint",0, "uint",c%A_Index% )
            h%A_Index% := DllCall( "CopyImage",  "uint",h_cursor, "uint",2, "int",0, "int",0, "uint",0 )
            b%A_Index% := DllCall("CreateCursor","uint",0, "int",0, "int",0
                , "int",32, "int",32, "uint",&AndMask, "uint",&XorMask )
        }
    }
    if (OnOff = 0 or OnOff = "Off" or $ = "h" and (OnOff < 0 or OnOff = "Toggle" or OnOff = "T"))
        $ = b  ; use blank cursors
    else
        $ = h  ; use the saved cursors

    Loop %c0%
    {
        h_cursor := DllCall( "CopyImage", "uint",%$%%A_Index%, "uint",2, "int",0, "int",0, "uint",0 )
        DllCall( "SetSystemCursor", "uint",h_cursor, "uint",c%A_Index% )
    }
}
</details>

**Comment by setsumi** [comment]
I'd like to know the full details of real world usage of such feature because currently I just don't know what to do. Without grasping the reason behind there are uncertainties of implementation details (like collision with the current GUI) and it is unclear if it worth implementing here at all since the script already exists.
